name: Code Linting

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Lint

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ mnatrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run build
        run: yarn build

      - name: Run ESlint
        run: yarn lint --fix
